// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelemetriaPCan.Infrastructure.Data;

#nullable disable

namespace TelemetriaPCan.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626190032_add_column_createdat_telemetry")]
    partial class add_column_createdat_telemetry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TelemetriaPCan.Domain.Entities.Telemetry", b =>
                {
                    b.Property<string>("IdTelemetry")
                        .HasColumnType("VARCHAR(40)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("FuelLevel")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int>("IdVehicle")
                        .HasColumnType("int");

                    b.HasKey("IdTelemetry");

                    b.HasIndex("IdVehicle");

                    b.ToTable("Telemetry", (string)null);
                });

            modelBuilder.Entity("TelemetriaPCan.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("IdVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVehicle"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Vin")
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("IdVehicle");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("TelemetriaPCan.Domain.Entities.Telemetry", b =>
                {
                    b.HasOne("TelemetriaPCan.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("IdVehicle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
